config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    get 'topics/unassign_team' => 'topics#unassign_team', as: :unassign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    get 'internal_docs/search' => 'internal_categories#search', as: :internal_docs_search

    resources :categories do
      resources :docs, except: [:index, :show]
    end


    resources :internal_categories, only: [:index, :show] do
      resources :internal_docs, only: :show
    end

    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController

  before_action :verify_admin, except: ['index', 'profile']
  before_action :verify_agent, only: ['index']
  skip_before_action :verify_authenticity_token

  def index
    @settings = AppSettings.get_all
    render layout: "admin"
  end

  def general
    render layout: 'admin-settings'
  end

  def design
    render layout: 'admin-settings'
  end

  def theme
    @themes = Theme.find_all
    render layout: 'admin-settings'
  end

  def widget
    render layout: 'admin-settings'
  end

  def i18n
    render layout: 'admin-settings'
  end

  def email
    render layout: 'admin-settings'
  end

  def integration
    # Set the webhook key if its blank
    AppSettings["webhook.form_key"] = SecureRandom.hex if AppSettings["webhook.form_key"].blank?
    render layout: 'admin-settings'
  end

  def profile
    @user = User.find(current_user)
    tracker("Agent: #{current_user.name}", "Editing User Profile", @user.name)
    render layout: 'admin-settings'
  end

  def preview
    theme = Theme.find(params[:theme])
    send_file File.join(theme.path, theme.thumbnail),
            type: 'image/png', disposition: 'inline', stream: false
  end

  def update_settings
    # NOTE: We iterate through settings here to establish our universe of settings to save
    # this means if you add a setting, you MUST declare a default value in the "default_settings intializer"
    @settings = AppSettings.get_all
    # iterate through
    @settings.each do |setting|
      AppSettings[setting[0]] = params[setting[0].to_sym] if params[setting[0].to_sym].present?
    end

    @logo = Logo.new
    @logo.file = params['uploader.design.header_logo']
    @logo.save

    @thumb = Logo.new
    @thumb.file = params['uploader.design.favicon']
    @thumb.save

    flash[:success] = t(:settings_changes_saved,
                        site_url: AppSettings['settings.site_url'],
                        default: "The changes you have been saved.  Some changes are only visible on your helpcenter site: #{AppSettings['settings.site_url']}")
    respond_to do |format|
      format.html {
        redirect_to admin_settings_path
      }
      format.js {
      }
    end
  end


end

app/controllers/api/v1/settings.rb
module API
  module V1
    class Settings < Grape::API

      before do
        authenticate!
        restrict_to_role %w(admin)
      end

      include API::V1::Defaults
      resource :settings, desc: "See and edit site settings" do

        # throttle max: 200, per: 1.minute

        # LIST ALL SETTINGS
        desc "List all settings and their values"
        params do
        end
        get "", root: :settings do
          settings = AppSettings.get_all
          present settings
        end

        # UPDATE SETTING
        desc "Update a setting value"
        params do
          requires :key, type: String
          requires :value, type: String
        end
        post "", root: :settings do
          AppSettings[params[:key]] = params[:value]
          present AppSettings[params[:key]]
        end

      end

    end
  end
end

app/views/admin/settings/design.html.erb
<% content_for :settings do %>

  <div class="admin-header">
    <h2><%= "#{t(:settings, default: "Settings")}: #{t(:design, default: "Design")}" %></h2>
  </div>

  <%= bootstrap_form_tag url: admin_update_settings_path, method: 'put', multipart: true, authenticity_token: true do |f| %>
    <div class="settings-section design">
        <div class="row">
          <div class="col-md-1 col-sm-2 col-xs-2">
            <%= image_tag(AppSettings['design.header_logo'], width: 40, class: 'pull-left') %>
          </div>
          <div class="col-md-11 col-sm-10 col-xs-10">
            <%= f.file_field 'uploader.design.header_logo', class: "settings-uploader", label: t('header_logo', default: "Header Logo") %>
            <%= f.text_field 'design.header_logo', class: "hidden-header-logo", value: AppSettings['design.header_logo'], hide_label: true %>
          </div>
        </div>
        <!-- <div class="row">
          <div class="col-md-1 col-sm-2 col-xs-2">
            <%= image_tag(AppSettings['design.footer_mini_logo'], width: 20, class: 'pull-left') %>
          </div>
          <div class="col-md-11 col-sm-10 col-xs-10">
            <%= f.file_field 'design.footer_mini_logo', value: AppSettings['design.footer_mini_logo'], label: t('footer_logo', default: "Footer Logo") %>
          </div>
        </div> -->
        <div class="row">
          <div class="col-md-1 col-sm-2 col-xs-2">
            <%= image_tag(AppSettings['design.favicon'], width: 32, class: 'pull-left') %>
          </div>
          <div class="col-md-11 col-sm-10 col-xs-10">
            <%= f.file_field 'uploader.design.favicon', class: "favicon-uploader", label: "Favicon" %>
            <%= f.text_field 'design.favicon', class: "hidden-favicon", value: AppSettings['design.favicon'], hide_label: true %>
          </div>
        </div>
        <% if AppSettings['theme.active'] == 'helpy' %>
          <%= f.text_field 'css.search_background', value: AppSettings['css.search_background'], label: t('search_background', default: "Search Background Color"), class: 'pick-a-color' %>
          <%= f.text_field 'css.top_bar', value: AppSettings['css.top_bar'], label: t('top_bar', default: "Header Accent"), class: 'pick-a-color' %>
          <%= f.text_field 'css.link_color', value: AppSettings['css.link_color'], label: t('link_color', default: "Link Color"), class: 'pick-a-color' %>
          <%= f.text_field 'css.form_background', value: AppSettings['css.form_background'], label: t('form_background', default: "Add Form Background"), class: 'pick-a-color' %>
          <%= f.text_field 'css.still_need_help', value: AppSettings['css.still_need_help'], label: t('still_need_help', default: "Still Need Help Background"), class: 'pick-a-color' %>
        <% else %>
          <%= f.text_field 'css.main_color', value: AppSettings['css.main_color'], label: t('search_background', default: "Search Background Color"), class: 'pick-a-color' %>
          <%= f.text_field 'css.accent_color', value: AppSettings['css.accent_color'], label: t('top_bar', default: "Header Accent"), class: 'pick-a-color' %>
          <%#= f.text_field 'css.link_color', value: AppSettings['css.link_color'], label: t('link_color', default: "Link Color"), class: 'pick-a-color' %>
          <%= f.text_field 'css.form_color', value: AppSettings['css.form_color'], label: t('form_background', default: "Add Form Background"), class: 'pick-a-color' %>
          <%#= f.text_field 'css.still_need_help', value: AppSettings['css.still_need_help'], label: t('still_need_help', default: "Still Need Help Background"), class: 'pick-a-color' %>
        <% end %>
        <%= f.text_area 'design.css', value: AppSettings['design.css'], label: "Custom CSS Styles", rows: 10, class: 'css-editor' %>
        <%= f.text_area 'design.header_js', value: AppSettings['design.header_js'], label: "Head Javascript", rows: 10, class: 'css-editor' %>
        <%= f.text_area 'design.footer_js', value: AppSettings['design.footer_js'], label: "Footer Javascript", rows: 10, class: 'css-editor' %>
    </div>
    <div class="submit-section">
      <%= f.submit "Save Settings", class: 'btn btn-warning' %>
    </div>

  <% end %>
<% end %>

app/views/admin/settings/email.html.erb
<% content_for :settings do %>

  <div class="admin-header">
    <h2><%= "#{t(:settings, default: "Settings")}: #{t(:email, default: "Email")}" %></h2>
  </div>

  <%= bootstrap_form_tag url: admin_update_settings_path, method: 'put', multipart: true, authenticity_token: true do |f| %>
    <div class="settings-section email" data-hook="admin_settings_email">
      <%= f.select 'email.mail_service',
        options_for_select([['Mailgun', 'mailgun'],['Sendgrid', 'sendgrid'],['Mandrill','mandrill'],['Postmark','postmark'],['Sparkpost','sparkpost'],['Amazon SES','ses']], AppSettings['email.mail_service']),
        label: t('mail_service', default: "Inbound Mail Service Provider") %>

      <%= f.form_group 'email.send_email', label: { text: t('send_email', default: "Enable Outbound (SMTP) Email") }, class: 'send-email-toggle' do %>
        <%= f.radio_button 'email.send_email', false, label: t('boolean_no', default: "No"), checked: "#{AppSettings['email.send_email']}" == 'false', class: 'send-email' %>
        <%= f.radio_button 'email.send_email', true, label: t('boolean_yes', default: "Yes"), checked: "#{AppSettings['email.send_email']}" == 'true', class: 'send-email' %>
      <% end %>
      <div class="smtp-settings <%= "hidden" if "#{AppSettings['email.send_email']}" == 'false' %>">
        <%= f.text_field 'email.admin_email', value: AppSettings['email.admin_email'], label: t('admin_email', default: "Admin Email") %>
        <%= f.text_field 'email.from_email', value: AppSettings['email.from_email'], label: t('from_email', default: "From Email") %>
        <%= f.text_field 'email.smtp_mail_username', value: AppSettings['email.smtp_mail_username'], label: t('smtp_mail_username', default: "SMTP Username") %>
        <%= f.password_field 'email.smtp_mail_password', value: AppSettings['email.smtp_mail_password'], label: t('smtp_mail_password', default: "SMTP Password") %>
        <%= f.text_field 'email.mail_smtp', value: AppSettings['email.mail_smtp'], label: t('mail_smtp', default: "SMTP Server") %>
        <%= f.text_field 'email.mail_port', value: AppSettings['email.mail_port'], label: t('mail_port', default: "SMTP Port") %>
        <%= f.text_field 'email.mail_domain', value: AppSettings['email.mail_domain'], label: t('mail_domain', default: "SMTP Domain") %>
      </div>
    </div>
    <div class="submit-section">
      <%= f.submit "Save Settings", class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>

app/views/admin/settings/general.html.erb
<% content_for :settings do %>

  <div class="admin-header">
    <h2><%= "#{t(:settings, default: "Settings")}: #{t(:general, default: "General")}" %></h2>
  </div>

  <%= bootstrap_form_tag url: admin_update_settings_path, method: 'put', multipart: true, authenticity_token: true do |f| %>
    <div class="settings-section">
      <h4 class="settings-subsection">Self Service Site</h4>
      <%= f.text_field 'settings.site_name', value: AppSettings['settings.site_name'], label: t('site_name', default: "Site Name") %>
      <%= f.text_field 'settings.site_url', value: AppSettings['settings.site_url'], label: t('site_url', default: "Site URL") %>
      <%= f.text_field 'settings.parent_site', value: AppSettings['settings.parent_site'], label: t('parent_site', default: "Parent Site") %>
      <%= f.text_field 'settings.parent_company', value: AppSettings['settings.parent_company'], label: t('parent_company', default: "Parent Company") %>
      <%= f.text_field 'settings.site_tagline', value: AppSettings['settings.site_tagline'], label: t('site_tagline', default: "Site Tagline") %>
      <br/><br/>

      <h4 class="settings-subsection">Helpy Functions</h4>
      <%= f.check_box 'settings.forums', { checked: forums?, label: t('enable_forums', default: "Enable Community Forums"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
      <%= f.check_box 'settings.knowledgebase', { checked: knowledgebase?, label: t('enable_knowledgebase', default: "Enable Knowledgebase"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
      <%= f.check_box 'settings.tickets', { checked: tickets?, label: t('enable_tickets', default: "Enable Private Tickets"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
      <%= f.check_box 'settings.teams', { checked: teams?, label: t('enable_teams', default: "Enable Team Groups"), label_class: 'full-width subitem', class: 'bs-toggle', data: { size: 'mini' } } %>
      <%= f.check_box 'settings.welcome_email', { checked: welcome_email?, label: t('enable_welcome_email', default: "Send a welcome email to new users"), label_class: 'full-width subitem', class: 'bs-toggle', data: { size: 'mini' } } %>

    </div>
    <div class="submit-section">
      <%= f.submit "Save Settings", class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>

app/views/admin/settings/i18n.html.erb
<% content_for :settings do %>

  <div class="admin-header">
    <h2><%= "#{t(:settings, default: "Settings")}: #{t(:international, default: "International")}" %></h2>
  </div>

  <%= bootstrap_form_tag url: admin_update_settings_path, method: 'put', multipart: true, authenticity_token: true do |f| %>
    <div class="settings-section international" data-hook="admin_settings_international">
      <%= t('supported_locales', default: 'Supported Locales:') %>
      <% I18n.available_locales.sort.each do |locale| %>
        <%= f.check_box 'i18n.available_locales', { multiple: true, label: I18n.translate("language_name", locale: locale.to_s), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' }, checked: AppSettings['i18n.available_locales'].include?(locale.to_s) }, "#{locale}", nil  %>
      <% end %>
      <br/>
      <div class='form-group'>
        <%= label_tag 'i18n.default_locale', t('default_locale', default: "Default Locale"), class: 'control-label' %>
        <%= f.select_tag 'i18n.default_locale', default_locale_options, class: 'form-control', id: 'i18n.default_locale' %>
      </div>
    </div>
    <div class="submit-section">
      <%= f.submit "Save Settings", class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>

app/views/admin/settings/index.html.erb
<% title "#{admin_title} #{t('settings', default: 'System Settings')}" %>
<% if current_user.is_admin? %>
<div class="admin-header">
  <h2 id="setting-header">
    <%= t('settings', default: 'System Settings') %>
  </h2>
</div>

<div class="settings-grid">
  <div class="settings-grid-row row">
    <%= content_tag :div, nil, class: 'col-md-1 hidden-xs hidden-sm' %>
    <div class="grids col-md-11 col-sm-12">
      <div class="row" data-hook="admin_settings_grid">
        <%= settings_item('glyphicon glyphicon-cog', "general", t('general_description', default: "Manage general system settings like your Helpy name, what company to link back to."), admin_general_settings_path) %>
        <%= settings_item('glyphicon glyphicon-pencil', "design", t('design_description', default: "Control the logos and colors and other design aspects of your Helpy"), admin_design_settings_path) %>
        <%= settings_item('fa fa-clone', "theme", t('theme_description', default: "Select a theme for your Helpy"), admin_theme_settings_path) %>
        <%= settings_item('glyphicon glyphicon-globe', "international", t('international_description', default: "Select what languages your Helpy will speak be able to speak."), admin_i18n_settings_path) %>
        <%= settings_item('glyphicon glyphicon-modal-window', "widget", t('widget_description', default: "Find out how to deploy the Helpy widget on your site."), admin_widget_settings_path) %>
        <%= settings_item('glyphicon glyphicon-envelope', "email", t('email_description', default: "Set up SMTP and Inbound email for your Helpy."), admin_email_settings_path) %>
        <%= settings_item('fa fa-cogs', "integrations", t('integrations_description', default: "Configure integrations with external services."), admin_integration_settings_path) %>
        <%= settings_item('fa fa-users', "customers", t('users_description', default: "See and invite your customers"), admin_users_path(role: 'user')) %>
        <%= settings_item('fa fa-briefcase', "team", t('users_description', default: "View and edit your support team"), admin_users_path(role: 'team')) %>
        <%= settings_item('glyphicon glyphicon-tags', t('team_group', default: "Groups"),
          t('group_description', default: "Edit, Delete, Create team list."), admin_groups_path) %>
        <%= settings_item('fa fa-reply', t('common_replies', default: "Common Replies"), t('common_replies_description', default: "View Common Replies"), admin_category_path(1)) %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/settings/integration.html.erb
<% content_for :settings do %>

  <div class="admin-header">
    <h2>Integrations</h2>
  </div>

  <%= bootstrap_form_tag url: admin_update_settings_path, method: 'put', multipart: true, authenticity_token: true do |f| %>
    <div class="settings-section integrations" data-hook="admin_settings_integrations">
      <div class="row integration-item vcenter">
        <div class="col-md-6">
          <span class="more-important">Incoming Webhook</span>
          <p class="less-important">
            Create tickets from existing webforms by POSTing to a JSON webhook
            URL. Your secret URL is:<br/>
            <%= f.check_box 'webhook.form_enabled', { checked: (AppSettings['webhook.form_enabled'] == '1'), label: t('enable_webhook_url', default: "Enable Incoming Webhooks"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
            <h4></h4>
          </p>
        </div>
        <div class="col-md-6">
          <%= text_field_tag 'URL', '', value: "#{request.protocol}#{request.host_with_port}/webhook/form/#{AppSettings["webhook.form_key"]}/", class: 'form-control' %>
        </div>
      </div>
      <div class="row integration-item vcenter">
        <div class="col-md-6">
          <span class="more-important">Google Analytics</span>
          <p class="less-important">
            Send Helpdesk usage statistics into Google Analytics for reporting
            and visualization.
            <%= f.check_box 'settings.google_analytics_enabled', { checked: (AppSettings['settings.google_analytics_enabled'] == '1'), label: t('enable_google_analytics', default: "Enable Google Analytics"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
          </p>
        </div>
        <div class="col-md-6">
          <%= f.text_field 'settings.google_analytics_id', value: AppSettings['settings.google_analytics_id'], label: "Google Analytics ID" %>
        </div>
      </div>
      <div class="row integration-item vcenter">
        <div class="col-md-6">
          <span class="more-important">Recaptcha</span>
          <p class="less-important">
            Recaptcha helps protect your self service helpdesk from spam.
            <%= f.check_box 'settings.recaptcha_enabled', { checked: (AppSettings['settings.recaptcha_enabled'] == '1'), label: t('enable_recaptcha', default: "Enable Recaptcha"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
          </p>
        </div>
        <div class="col-md-6">
          <%= f.text_field 'settings.recaptcha_site_key', value: AppSettings['settings.recaptcha_site_key'], label: t('recaptcha_site_key', default: "Recaptcha Site Key") %>
          <%= f.text_field 'settings.recaptcha_api_key', value: AppSettings['settings.recaptcha_api_key'], label: t('recaptcha_api_key', default: "Recaptcha API Key") %>
        </div>
      </div>
      <div class="row integration-item vcenter">
        <div class="col-md-6">
          <span class="more-important">Cloudinary</span>
          <p class="less-important">
            Cloudinary offers image hosting and transformation services.
            <%= f.check_box 'cloudinary.enabled', { checked: (AppSettings['cloudinary.enabled'] == '1'), label: t('enable_cloudinary', default: "Enable Cloudinary"), label_class: 'full-width', class: 'bs-toggle', data: { size: 'mini' } } %>
          </p>
        </div>
        <div class="col-md-6">
          <%= f.text_field 'cloudinary.cloud_name', value: AppSettings['cloudinary.cloud_name'], label: "Cloudinary Cloud Name" %>
          <%= f.text_field 'cloudinary.api_key', value: AppSettings['cloudinary.api_key'], label: "Cloudinary API Key" %>
          <%= f.password_field 'cloudinary.api_secret', value: AppSettings['cloudinary.api_secret'], label: "Cloudinary API Secret" %>
        </div>
      </div>

    </div>
    <div class="submit-section">
      <%= f.submit "Save Settings", class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>

app/views/admin/settings/profile.html.erb
<% title "#{admin_title} #{t(:discussions, default: "Discussions")}" %>

<% content_for :settings do %>
  <h2 id="ticket-page-title">
    <%= @user.name.titleize %>
    <%= "<br/>#{content_tag(:small, "Account: " + @user.account_number)}".html_safe if @user.account_number.present? %>
  </h2>
  <div id="user-info">
    <%= render 'admin/users/edit' %>
  </div>
  <div class="row">
    <div class="col-md-12" id="tickets">
    </div>
  </div>
<% end %>

app/views/admin/settings/theme.html.erb
<% content_for :settings do %>

  <div class="admin-header">
    <h2><%= "#{t(:settings, default: "Settings")}: #{t(:theme, default: "Theme")}" %></h2>
  </div>

  <%= bootstrap_form_tag url: admin_update_settings_path, method: 'put', multipart: true, authenticity_token: true do |f| %>
    <div class="settings-section theme">
      <div class="row">
        <% @themes.each do |theme| %>
        <div class="col-md-4" class="theme-item">
          <%= f.radio_button 'theme.active', theme.name, checked: theme.name == AppSettings['theme.active'], label: theme.name.titleize %>
          <%= image_tag(url_for(action: 'preview', theme: theme.name))  %>
          <%= theme.description %> <%= link_to "[Preview]", root_url(theme: theme.name), target: '_blank' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="submit-section">
      <%= f.submit "Save Settings", class: 'btn btn-warning' %>
    </div>
  <% end %>
<% end %>